name: Publish to Chrome Web Store
run-name: ${{ github.actor }} is publishing a new extension version
on:
  release:
    types: [published] # Triggers when you publish a GitHub Release

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:bundle

      - name: Install Zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Zip extension
        run: |
          cd distribution
          zip -r ../extension.zip .

      - name: Publish to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'publish' 
          client_id: ${{ secrets.CLIENT }}
          client_secret: ${{ secrets.SECRET }}
          refresh_token: ${{ secrets.TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: 'extension.zip'